package io.github.palprz;

import io.github.palprz.autogenerated.RequestMsg;
import io.github.palprz.autogenerated.ResponseMsg;
import io.github.palprz.autogenerated.ResultServiceGrpc;
import io.grpc.stub.StreamObserver;

public class ResultServiceImpl extends ResultServiceGrpc.ResultServiceImplBase {

    @Override
    public void transfer(
            RequestMsg request, StreamObserver<ResponseMsg> responseObserver) {

        String result = "Hi, " + request.getFirstName() + " " + request.getLastName()
                + "! This is a response from the server side.";

        ResponseMsg response = ResponseMsg.newBuilder()
                .setResult(result)
                .build();

        responseObserver.onNext(response);
        responseObserver.onCompleted();
    }
}